---
# tasks file for jboss-eap
#
- name: Install JBoss EAP
  yum:
    name: "@jboss-eap7"
    state: latest
  notify:
    - Start JBoss EAP

- name: Enable JBoss Standalone Service
  service: 
    name: eap7-standalone
    enabled: yes
    state: started

- name: Enable Jboss EAP Firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 8080/tcp
    - 8443/tcp
    - 9990/tcp
    - 9999/tcp

