---
# tasks file for jboss-eap
#
- name: Install JBoss EAP
  yum:
    name: "@jboss-eap7"
    state: latest
  notify:
    - Start JBoss EAP

- name: Enable JBoss Domain Service
  service: 
    name: eap7-domain
    enabled: yes
    state: started

- name: Disable JBoss Staandalone Service
  service: 
    name: eap7-standalone
    enabled: no
    state: stopped

- name: Enable Jboss EAP Firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 8080/tcp
    - 8443/tcp
    - 9990/tcp
    - 9999/tcp

- name: Copy master config
  copy: src=host-master.xml dest=/etc/opt/rh/eap7/wildfly/domain/host.xml
    backup: yes
  when: inventory_hostname == "jboss0.example.com"
  notify: 
    - Reload JBoss EAP

- name: Copy slave config
  copy: src=host-slave.xml dest=/etc/opt/rh/eap7/wildfly/domain/host.xml
    backup: yes
  when: inventory_hostname == "jboss1.example.com"
  notify: 
    - Reload JBoss EAP

- name: Copy user properties config
  copy: src=mgmt-users.properties dest=/etc/opt/rh/eap7/wildfly/domain/mgmt-users.properties
    backup: yes
  notify: 
    - Reload JBoss EAP

- name: Copy domain config
  copy: src=domain.xml dest=/etc/opt/rh/eap7/wildfly/domain/domain.xml
    backup: yes
  notify: 
    - Restart JBoss EAP

