---
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify:
    - Start Nginx

- name: Enable Nginx
  service: 
    name: nginx
    enabled: yes
    state: started

- name: Enable Nginx Firewalld http port
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: yes

- name: Enable Nginx Firewalld https port
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
    immediate: yes

