---
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify:
    - Start Nginx

- name: Enable Nginx
  service: 
    name: nginx
    enabled: yes
    state: started

- name: Enable Nginx Firewalld ports
  firewalld:
    port: "{{ items }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 80/tcp
    - 443/tcp

