---
- name: Install Nginx
  yum:
    name: nginx
    state: latest
  notify:
    - Start Nginx

- name: Enable Nginx
  service: 
    name: nginx
    enabled: yes
    state: started

- name: Enable Nginx Firewalld ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - 80/tcp
    - 443/tcp

- name: Copy Nginx-JBoss config
  copy:
    src: jboss.conf
    dest: /etc/nginx/conf.d/jboss.conf
    backup: yes
  notify:
    - Reload Nginx
