---
# tasks file for rhel
#

- name: Copy hosts file
  copy:
    src: hosts
    dest: /etc/hosts
    backup: yes


- name: Copy Yum local repos
  copy:
    src: infra_migration.repo
    dest: /etc/yum.repos.d/infra_migration.conf
    backup: yes


