---

- hosts: app
  tasks:
  - name: Subscribe app VMs
    redhat_subscription:
      state: present
      username: "{{rhn_username}}"
      password: "{{rhn_password}}"
      pool_ids: "{{rhn_pool_ids}}"

  - name: Configure repos
    command: subscription-manager repos --disable='*' --enable='rhel-x86_64-server-7' --enable='rhel-x86_64-server-extras-7' --enable='rhel-x86_64-server-optional-7'

  - name: Update app VMs
    yum:
      name: '*'
      state: latest
