---

- hosts: app
  tasks:
  - name: Subscribe app VMs
    redhat_subscription:
      state: present
      username: "{{rhn_username}}"
      password: "{{rhn_password}}"
      pool_ids: "{{rhn_pool_ids}}"

  - name: Configure repos
    command: subscription-manager repos --disable='*' --enable='rhel-7-server-rpms' --enable='rhel-7-server-extras-rpms' --enable='rhel-7-server-optional-rpms'

  - name: Update app VMs
    yum:
      name: '*'
      state: latest
