---
# tasks file for jboss-eap
#
- name: Install JBoss EAP
  yum:
    name: "@jboss-eap7"
    state: latest
  notify:
    - Start JBoss EAP

- name: Enable JBoss Standalone Service
    service: 
      name: eap-standalone
      enabled: yes
      state: started
